### ISSUE TITLE
recipe for dupeGuru fails

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/flammable-recipes#7]
Running `dupeGuru.munki` gives

```
SparkleUpdateInfoProvider
Error parsing XML from appcast feed.
Failed.

```

Could you please update this recipe?

**Comment by flammable** [comment]
Hi! So, this recipe is based on the Sparkle feed for dupeGuru. Since then, the developer has passed along development to a new developer, who has not yet implemented a new Sparkle feed.

The new URL is here, if you'd like to manually download 4.0.3, which was the last release from Hardcoded Software:

https://dupeguru.voltaicideas.net

This is the GitHub issue to watch for version 4.0.4's release:

https://github.com/arsenetar/dupeguru/issues/566

Until 4.0.4 is released, it's probably not worth the time that would be required to rewrite the recipe.

**Comment by flammable** [comment]
Update: the new developer [requested help with maintaining the Cocoa app](https://dupeguru.voltaicideas.net/2021/08/14/macOS_releases_going_forward.html), but [encountered issues](https://github.com/arsenetar/dupeguru/issues/945).

This AutoPkg recipe hasn't worked for some time, but I don't see a way to update it in the future. [This looks like the current way to install dupeGuru on the Mac.](https://github.com/arsenetar/dupeguru/blob/master/macos.md)

I added a DeprecationWarning to the `com.github.flammable.download.dupeGuru` recipe, and will remove both from the repo at some point. Closing this issue and #9. Sorry.
